### ISSUE TITLE
[2.2.0-1] listening on loopback address

### ISSUE THREAD

**Issue by levkkuro** [STNS/STNS#102]
stns-v2.x86_64 を 2.1.1-1 から 2.2.0-1 へバージョンアップ後、
特に設定を何も触らずにstnsをstartさせると、
自ホストからのアクセスしか受けつけないようになっていました(2.1.1-1 では :::1104 )。
stns.confや起動オプションに新しい設定が加わったでしょうか？
```
# netstat -anp | grep stns
tcp        0      0 127.0.0.1:1104              0.0.0.0:*                   LISTEN      23553/stns
```

**Comment by pyama86** [comment]
わ、間違ってコミットしてしまっている可能性が高いです。ちょい直してすぐリリースします。

**Comment by levkkuro** [comment]
正確にお伝えすると tcp6 が tcp となります。
* v2.1.1-1
```
# netstat -anp | grep stns
tcp6       0      0 :::1104                 :::*                    LISTEN      3200/stns
```

* v2.2.0-1
```
# netstat -anp | grep stns
tcp        0      0 127.0.0.1:1104          0.0.0.0:*               LISTEN      3437/stns
```

**Comment by pyama86** [comment]
はい、僕が開発時にlocalhostで開発してるのでそのままビルドしてしまったっぽいです。今リリースしてるので今しばらくお待ち下さい。

**Comment by pyama86** [comment]
今ほど再リリースしました。近日中にListenを環境変数から持っていけるようにする予定なので、今後同じミスが起きなくなる予定です。失礼しました。

**Comment by levkkuro** [comment]
ありがとうございました！😄
