### ISSUE TITLE
Focal support...

### ISSUE THREAD

**Issue by june07** [STNS/STNS#116]
Any chance of adding support for Ubuntu Focal (20.04 LTS)?  Currently there doesn't seem to be a repo...

```
The repository 'https://repo.stns.jp/focal stns Release' does not have a Release file.
```

**Comment by pyama86** [comment]
Hi!
I will support Ubuntu focul and I'm releasing now.
You could try to install at 0:00 pm JST(may be)
Thanks!

**Comment by pyama86** [comment]
@june07 I have released now!

**Comment by june07** [comment]
WOW.  FAST turnaround!  Thank you.  And thanks for the great library.

**Comment by june07** [comment]
Maybe this was missed...
https://github.com/STNS/package/pulls
