### ISSUE TITLE
Has etcd support been dropped?

### ISSUE THREAD

**Issue by kaz** [STNS/STNS#118]
I found `modules/etcd.go` has been deleted recently.
https://github.com/STNS/STNS/commit/f9dfb06d8a2a770501511349e961eba8f202ca22#diff-9c0e163dab87662e7f9af416d70af877b480e9df5bb345dfeb7219dd3c937b2e

But I cannot find any announcements about this change.
etcd will no longer be supported?

**Comment by pyama86** [comment]
thank you for you feedback.

I'm shame because I made very easy misstake..

https://github.com/STNS/STNS/pull/119/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R17

However, I fixed it and I don't have any plan that stop support etcd!
