### ISSUE TITLE
リバースプロキシなしでstnsを利用した場合に、STNS Serverとcache-stnsdの間のTCPコネクションが増え続ける

### ISSUE THREAD

**Issue by hogesako** [STNS/STNS#122]
# 事象
リバースプロキシなしでstnsを利用した場合に、STNS Serverとcache-stnsdの間のTCPコネクションが増え続けます。(client側のhttp.TransportのIdleConnTimeoutデフォルト値との均衡が取れるまで増え続けていると思われます)

# 再現手順

## start up server and count tcp connection
```
docker run --name stns_tcp_keepalive -p 1104:1104 --rm stns/stns

docker exec -it stns_tcp_keepalive bash
apt-get -qqy update && apt-get install -qqy net-tools
watch "netstat -antp | grep 1104 | wc -l"
```

## 以下を実行
```
package main

import (
	"time"

	"github.com/STNS/libstns-go/libstns"
)

func main() {
	for i := 0; i < 10000000; i++ {
		stns, err := libstns.NewSTNS("http://localhost:1104/v1/", nil)
		if err != nil {
			panic(err)
		}
		stns.ListUser()
		time.Sleep(time.Millisecond * 100)
	}
}
```

# その他
https://github.com/STNS/libstns-go/blob/master/libstns/client.go#L131
あたりで `tr.CloseIdleConnections()`  を実行すればTCPコネクションが増えなくなることを確認済みです。

**Comment by pyama86** [comment]
報告ありがとうございます。めちゃくちゃ助かります。もし手間でなければプルリクエスト貰えると嬉しいです。

**Comment by pyama86** [comment]
https://qiita.com/kitauji/items/b4e8a48c75bf01ccc9f0

この辺り見るとアイドルのコネクションが100がデフォルトっぽいからそこまで持つとかそういう話もありそうには思いました。
今手元に端末がないので完全にエスパーです。

**Comment by hogesako** [comment]
先述の再現手順を実行するとコネクション数が100を超えることを確認しております。
TransportのインスタンスごとにTCPコネクションやMaxIdleConnsを管理しているように見えます。

デフォルトのファイルディスクリプタ上限が1024みたいなOSだとすぐにtoo many open filesが出ちゃいそうな感じがしています。

**Comment by hogesako** [comment]
cache-stnsdを読んでいたら、libstns-goの使い方が違うことに気づきました。失礼しました。
正しくは以下です。(これでも再現します)
```
package main

import (
	"time"

	"github.com/STNS/libstns-go/libstns"
)

func main() {
	stns, err := libstns.NewSTNS("http://localhost:1104/v1/", nil)
	if err != nil {
		panic(err)
	}
	for i := 0; i < 10000000; i++ {
		stns.Request("/status", "")
		time.Sleep(time.Millisecond * 100)
	}
}
```

**Comment by pyama86** [comment]
PRありがとうございました!
日本時間の2/1にリリースします！

**Comment by pyama86** [comment]
cache-stnsd_0.3.10-1をリリースしました。
