### ISSUE TITLE
STNSの利用によりこの構成が実現可能かを教えていただくこと出来ますでしょうか？

### ISSUE THREAD

**Issue by act-node** [STNS/STNS#126]
次の様なシナリオケースでSTNSが利用できないかを検討しています。
![image](https://user-images.githubusercontent.com/59199162/132380490-8218f801-1e38-4573-be33-6a27ff7a8669.png)

1. DynamoDBに書き込まれたID/PWを参照してSTNS経由でのPAMによるユーザー認証が可能でしょうか？
2. 認証が可能な場合、stnsからのレスポンスによってログインユーザー(ID)のアクセス制御を行う際に、
　STNSをどの様に使用するのが良いと考えられるでしょうか？

**Comment by pyama86** [comment]
1.可能です。また、STNSにDynamoDB moduleがあるので、Redisと組み合わせるとシンプルに構築できると思います。
2.STNS/STNS、STNS/libnssが提供するのはuser/groupの名前解決なので、アクセス制御をやるのはpamなどのミドルウェアになると思います。
