### ISSUE TITLE
apt-key is deprecated command

### ISSUE THREAD

**Issue by tororoMeshi** [STNS/STNS#201]
Envioments
- Ubuntu 22.04.2 LTS
- Kernel : 5.15.0-75-generic
- CPU : x86_64

When I executed the install script for DEBIAN/UBUNTU, the following error occurred.
```shell
W: https://repo.stns.jp/jammy/dists/stns/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

apt-key command is deprecated according to `man apt-key 8`.
```shell
DEPRECATION
       Except for using apt-key del in maintainer scripts, the use of apt-key is deprecated. This section shows how to
       replace existing use of apt-key.

       If your existing use of apt-key add looks like this:

       wget -qO- https://myrepo.example/myrepo.asc | sudo apt-key add -

       Then you can directly replace this with (though note the recommendation below):

       wget -qO- https://myrepo.example/myrepo.asc | sudo tee /etc/apt/trusted.gpg.d/myrepo.asc
```

Thank you.

[ref]
https://github.com/STNS/STNS/blob/f7faadb05662c682bbba8b0b6f4ef9504e04e7cb/package/scripts/apt-repo.sh#L12C16-L12C16

**Comment by pyama86** [comment]
Yes, I am aware of that, but there is also the issue of backward compatibility, which I will address when the time is right.
