### ISSUE TITLE
Add Support for Ubuntu 24.04 LTS (Noble)

### ISSUE THREAD

**Issue by salmon111** [STNS/STNS#269]
Hi!

I'm excited about the upcoming release of Ubuntu 24.04 LTS, codenamed Noble.
It would be fantastic if this project could support this new version as soon as it's available.
Is there any plan to ensure compatibility with Noble once it's released?
```
E: The repository 'https://repo.stns.jp/noble stns Release' does not have a Release file.
```

Thanks!

**Comment by pyama86** [comment]
Leave it to me, brother. I'm free right now, so I'll handle it.

**Comment by pyama86** [comment]
https://github.com/STNS/package/actions/runs/8812087589

Once this task is completed, you can try it out.
