### ISSUE TITLE
STNS server / client TLS support

### ISSUE THREAD

**Issue by naototty** [STNS/STNS#35]
STNS http protocol is basic auth raw http.
https is more better security.

**Comment by pyama86** [comment]
I appreciate all of your help nowadays.

> https is more better security.
I think so too. I think that it is essential to managing that it was closed in the global network.
I implement it, wait a minute

japanese
STNS自体はNginxなどと組み合わせてhttpsで運用することを想定していますが、TLS認証を実装しておけばグローバルNWにSTNSを置いて運用する場合、有用だと思うので実装します。

**Comment by pyama86** [comment]
STNS,libnss-stns 0.2.2 released.
Feature in this release is included.
thank you!
