### ISSUE TITLE
Cannot use dots in username.

### ISSUE THREAD

**Issue by etsnakano** [STNS/STNS#41]
Hi, STNS is great project!
By the way, STNS cannot find "dots included" username.

```
### CONF
$ cat /etc/stns/users.d/1000.conf
[users."dot.user"]
id = 1000
group_id = 1000
shell = "/bin/bash"
directory = "/home/user/dot.user"

### TEST
$ curl --user 'BASIC_AUTH' http://127.0.0.1:1104/v2/user/name/dot.user
{
  "Error": "Resource not found"
}
```

Dots are supported at key: [TOML](https://github.com/toml-lang/toml).
> Dots are prohibited in bare keys because dots are used to signify nested tables. Naming rules for each dot separated part are the same as for keys (see definition of Key/Value Pairs).
>
>[dog."tater.man"]
>type = "pug"
>
>In JSON land, that would give you the following structure:
>
>{ "dog": { "tater.man": { "type": "pug" } } }

-- Japanese --
STNSは素晴らしいプロジェクトですね。
ところで、STNSでドットを含むユーザー名が使用できません。
TOML書式ではキーでのドットは許可されているようです。

**Comment by pyama86** [comment]
Hi!
I did not know that `.` Should be included in the Linux user name.

```
[root@example ~]# useradd hoge.fuga
[root@example ~]# id hoge.fuga
uid=902(hoge.fuga) gid=902(hoge.fuga) groups=902(hoge.fuga)
```
Please wait for a while until correspondence


-- Japanese --
issue有難うございます！
Linuxのユーザー名に`.`が含めることを存じておらず、対応できていませんでした。
対応したいと思うのでしばらくお待ち下さい。

**Comment by etsnakano** [comment]
Thank you.
I tested curl to `v2/user/list`, it returned collect answers. TOML parser works well, I guess.

```
$ curl --user 'BASIC_AUTH' http://127.0.0.1:1104/v2/user/list
```

-- Japanese --
ご対応いただきありがとうございます！
ユーザーリストをcurlで取得すると正常に帰ってきますので、TOMLパーサーは正常動作している気がします。
よろしくお願いします！

**Comment by pyama86** [comment]
`.`でパースされているのと
https://github.com/ant0ine/go-json-rest/blob/master/rest/trie/impl.go#L19

以前PRが出ていてクローズしているのを見ると、
https://github.com/ant0ine/go-json-rest/pull/45
サーバ側で頑張るより、クライアント側でエンコードしてAPI実行するのが筋が良さそうですね。

**Comment by pyama86** [comment]
We released 0.3-1. After this version it will be possible to include a period in the user name
```
# id example.1
uid=1001(example.1) gid=1001(example) groups=1001(example)
# getent passwd example.1
example.1:x:1001:1001::/home/example:/bin/bash
```

-- Japanese --
urlエンコードを追加し、`.`をユーザー名に含めるよう対応しました。
0.3-1以降で利用可能なので、ご確認ください！

**Comment by etsnakano** [comment]
Great! I tested '0.3-1' and saw it worked fine!
Thank you!

--- Japanese ---
0.3-1を試して無事に動くのを確認できました！
早急な対応ありがとうございました！
