### ISSUE TITLE
Windowsのsshクライアントについて

### ISSUE THREAD

**Issue by miya-sun** [STNS/STNS#54]
有用なツールを公開してくださりありがとうございます。

ゲストユーザー向けにsshアカウントを払い出す仕組みを想定し、stnsを利用してユーザーの管理をしている別システムから情報を取得し、ログインさせる仕組みを実装しました。  
（ゲストユーザーなので、パスワード認証を使うよう設定しました）

テストの際に気がついたのですが、linux（macOSを含む）系のクライアントの接続は問題なく処理され、サーバにログインできるのですが、windowsのクライアントだとパスワードの入力後応答がなくなってしまい、端末がハングしたかのような状態となってしまいます。

動作を確認したwindowsのsshクライアント  
- teratem
- putty
- pederosa
- cygwimのsshコマンド

sshクライアントのデバッグログ、stnsの動いているサーバのsyslog等も確認しましたが、明確な形でエラーとはなっておらず、クライアント、またはサーバどちらかの応答を待っているような状態になっているようでした。

ログレベルの確認方法ですと、行き詰まりを感じており一旦 Issues を上げさせていただきました。お手数ではございますが、ご確認、またはアドバイスが頂けると助かります。

## システム構成等
OS：CentOS Linux release 7.4.1708 （VMware仮想化環境上に構築しています）

## 仕様
簡単ではありますが、以下に動作仕様を記載します。

- ユーザーを管理している別システムにワンタイムアカウントを発行する機能、取得のためのAPIを実装する。
- libnss_stnsのラッパースクリプトからAPIコールしてユーザー情報を取得しそれを使用して認証情報として返すようにする。
- libpam-stns等を設定し、sshの認証を成功させるような仕組みになります。

このため、サーバーとしてのstnsは起動しておりません。また、nscdも未使用状態です。

ワンタイムアカウントなので、共通鍵認証については利用せずパスワード認証で動作をさせています。（キーラッパー等は使用していない形となります）

## ログ等（一部抜粋）

クライアント側  （Cygwinのsshクライアント -vvv付き）
~~~
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network

以降、ログの出力は無し画面は無反応

~~~

サーバー側  
~~~
debug1: monitor_child_preauth: IOKkniDl has been authenticated by privileged process
debug3: mm_get_keystate: Waiting for new keys
debug3: mm_request_receive_expect entering: type 26
debug3: mm_request_receive entering
debug3: mm_get_keystate: GOT new keys
debug3: mm_request_receive_expect entering: type 122
debug3: mm_request_receive entering
debug3: mm_request_send entering: type 123
debug3: mm_auth_password: user authenticated [preauth]
debug3: mm_do_pam_account entering [preauth]
debug3: mm_request_send entering: type 102 [preauth]
debug3: mm_request_receive_expect entering: type 103 [preauth]
debug3: mm_request_receive entering [preauth]
debug3: mm_do_pam_account returning 1 [preauth]
debug3: send packet: type 52 [preauth]
debug3: mm_request_send entering: type 26 [preauth]
debug3: mm_send_keystate: Finished sending state [preauth]
debug3: mm_request_send entering: type 122 [preauth]
debug3: mm_request_receive_expect entering: type 123 [preauth]
debug3: mm_request_receive entering [preauth]
debug1: monitor_read_log: child log fd closed
debug3: ssh_sandbox_parent_finish: finished
debug1: SELinux support disabled
debug1: PAM: establishing credentials
debug3: PAM: opening session
pam_unix(sshd:session): session opened for user IOKkniDl by (uid=0)
User child is on pid 10549


以降のログは出力されない
~~~

※ 設定ファイル等はlinux環境ではうまく接続できているため、多分問題ないのかなと考えておりますので、一旦割愛させていただきます。必要がありそうであれば言っていただければ追記いたします。

以上です。

**Comment by pyama86** [comment]
Issue有難うございます！sshdの挙動についてはnscdを起動いただくと、問題なくご利用いただけると思うので、ぜひお試しください！！！
