### ISSUE TITLE
localhostにsshするとgid0でホームディレクトリが出来るらしい

### ISSUE THREAD

**Issue by pyama86** [STNS/STNS#83]
https://twitter.com/n_siena/status/1066965461701582848

![image](https://user-images.githubusercontent.com/8022082/49000774-feb16c00-f19d-11e8-86fb-6de47619dbb7.png)
```
設定が悪いらしく、id -g test も id -G test も 10001 なのに、ssh -l test localhost すると pam_mkhomedir が gid=0 なホームディレクトリを作ってしまうので、curl する先を調べてて気になりました。
```

**Comment by nsiena** [comment]
STNSのレスポンスは期待通りで問題なかったようです。
```
$ curl http://localhost:1104/v1/users?name=test
#=> ... group_id=10001 ...
$ curl http://localhost:1104/v1/groups?name=test
#=> users に test が含まれているのは id=10001 だけ
```
sshログイン後も特に異常ないようです。
```
$ ssh -l test localhost
| $ id test
| #=> uid=10001(test) gid=10001(test) groups=10001(test)
```
というわけで、PAMの設定不備とかが怪しい感じなので、設定見直し中です。

**Comment by nsiena** [comment]
報告が遅れましたが、その後、よく分からないながらも、グループも正常なホームディレクトリが作成されるようになりました。残念ながら(?)、その後、現象を再現できていません。原因が分からず気持ち悪いですが、当初から STNS や `id` などは期待通りの挙動になっていたので、いったんクローズしていただいて、また何かあったら相談したいと思います。

参考までにやったことは次の通りです。
問題のあったインストール当日は当該の仮想マシンを停止させて、翌日に再開させてから、

* `/etc/pam.d/{system-auth,passwd-auth,sshd}` に `pam_mkhomedir` を加えたり消したり (最終的には元通りにした)、
* 何度か `systemctl restart sshd stns` したり、
* 何度かOSを再起動したり、

としただけで、これらの操作は前日に何度もしていたことの繰り返しなので、改善理由という確信は持てていません。
キャッシュやタイムスタンプのような時間経過に影響されるものだったのかもという気もしましたが、`pam_mkhomedir` の挙動を把握していないので的外れかもしれません。

**Comment by nsiena** [comment]
問題が起きて解消した後の環境は次の通りです。

* Windows 10 上の VirtualBox 上の [CentOS 7.5(1804) minimum](http://ftp.iij.ad.jp/pub/linux/centos/7.5.1804/isos/x86_64/CentOS-7-x86_64-Minimal-1804.iso)
	* サイトポリシーによりいろいろ設定変更あり
	* これらは問題解消後までに変更してないので、影響なしと考えて省略
* STNS リリース v.2.0.2
	* libnss-stns-v2-2.0.3-2.x86_64.el7.rpm
	* stns-v2-2.0.2-2.x86_64.el7.rpm

最終的な `/etc/{stns,pam.d/sshd,ssh/sshd_config}` だけ添付しておきます。

* [etc.zip](https://github.com/STNS/STNS/files/2622923/etc.zip)
	* pam.d/{system-auth,password-auth} にも念のため pam_mkhomedir を追加したこともあるけど、ssh 接続時にこれの有無は影響なかったので省略
	* stns.conf 内のパスワードハッシュは "xxxxxxxxxx" に差替え済
	* stns.conf 内のユーザ/グループは、最初は test/test だけで、他は (link_{users,groups} も含めて) 問題発生時の試行錯誤中に追加したもの (影響なし)

試行錯誤中の確認方法はこんな感じでした。

* サービスを再起動 (問題解消せず)
* OSを再起動 (問題解消せず)
* curl で stns からユーザ、グループ情報を取得して確認 (問題なし)
* `id test` したり、 `sudo rm -r /home/test && ssh -l test localhost` 後に `id` したり (問題なし)
* ssh ログアウト後に、`ls -ld /home/test` (gid=0 になってる)

とりあえず、VMはスナップショットを取っておいたので、他に必要な情報があれば追加提供できると思います。

**Comment by pyama86** [comment]
こちらでも環境作ってみたのですが再現できず。。。起こりそうなのはキャッシュ周りで謎なレコードできてとかありそうなんで、僕も運用しながら再発待ってみます。一旦クローズします。詳細な報告大変助かりました。
